@startuml SystemsContainer
!include <C4/C4_Container>

title Arquitetura de Sistema - Processamento com Filas Singulares, Storage e Produtor de Mensagens

Container(contentPlatform, "Content Platform", "Web/Mobile", "Plataforma de gerenciamento de conteúdo")

Container(bucketVideo, "Bucket de Videos", "S3/Blob Storage")
Container(bucketAudio, "Bucket de Áudios", "S3/Blob Storage")
Container(bucketTrans, "Bucket de Transcrições", "S3/Blob Storage")
Container(bucketTransl, "Bucket de Traduções", "S3/Blob Storage")

Container(storagePublisher, "Storage Publisher", "Service", "Publica eventos de armazenamento")
Container(contentStorageWatcher, "Observador de Armazenamento", "Serviço", "Orquestra e despacha tarefas")
Container(orchestrator, "Orquestrador de Workflows", "Serviço", "Gerencia o fluxo de trabalho de forma dinâmica e condicional")

Container(audioExtractor, "Serviço de Extração de Áudio", "Serviço", "Extrai áudio de vídeos")
Container(STT, "Serviço de Transcrição de Áudio", "Serviço", "Transcreve áudio em texto")
Container(translate, "Serviço de Tradução de Texto", "Serviço", "Traduz texto para outro idioma")
Container(TTS, "Serviço de Geração de Áudio", "Serviço", "Transforma texto em áudio")

ContainerQueue(contentStorageTopic, "Tópico de Armazenamento de Conteúdo", "RabbitMQ/Kafka/SQS", "Recebe solicitações para armazenamento de conteúdo")
ContainerQueue(audioExtractionJobTopic, "Tópico de Extração de Áudio", "RabbitMQ/Kafka/SQS", "Recebe solicitações para extração de áudio")
ContainerQueue(audioTranscriptionJobTopic, "Tópico de Transcrição de Áudio", "RabbitMQ/Kafka/SQS", "Recebe solicitações para transcrição de áudio")
ContainerQueue(textTranslationJobTopic, "Tópico de Tradução de Texto", "RabbitMQ/Kafka/SQS", "Recebe solicitações para tradução de texto")
ContainerQueue(textToSpeechJobTopic, "Tópico de Texto para Fala", "RabbitMQ/Kafka/SQS", "Recebe solicitações para transformação de texto em áudio")


Rel(contentPlatform, bucketAudio, "Armazena e recupera áudios", "down")
Rel(contentPlatform, bucketVideo, "Armazena e recupera vídeos", "down")

Rel(bucketVideo, storagePublisher, "Notifica Armazenamento", "right")
Rel(bucketAudio, storagePublisher, "Notifica Armazenamento", "right")
Rel(bucketTrans, storagePublisher, "Notifica Armazenamento", "right")
Rel(bucketTransl, storagePublisher, "Notifica Armazenamento", "right")

Rel(storagePublisher, contentStorageTopic, "Publica solicitação de armazenamento", "right")
Rel(contentStorageTopic, orchestrator, "Envia solicitação de processamento dinâmico", "right")

Rel(orchestrator, contentStorageWatcher, "Define fluxo de trabalho", "down")

Rel(contentStorageWatcher, audioExtractionJobTopic, "Envia solicitação de extração de áudio", "right")
Rel(contentStorageWatcher, audioTranscriptionJobTopic, "Envia solicitação de transcrição de áudio", "right")

Rel(audioExtractionJobTopic, audioExtractor, "Envia áudio para extração", "down")
Rel(audioExtractor, audioTranscriptionJobTopic, "Envia áudio para transcrição", "down")

Rel(audioTranscriptionJobTopic, STT, "Envia áudio para transcrição", "down")
Rel(STT, textTranslationJobTopic, "Envia texto para tradução", "right")

Rel(textTranslationJobTopic, translate, "Envia texto para tradução", "right")
Rel(translate, textToSpeechJobTopic, "Envia texto para transformação em áudio", "right")

Rel(textToSpeechJobTopic, TTS, "Envia texto para transformação em áudio", "down")
Rel(TTS, bucketAudio, "Armazena áudio", "up")

Rel(STT, bucketTrans, "Armazena transcrição", "up")
Rel(translate, bucketTransl, "Armazena tradução", "up")

Rel(orchestrator, audioExtractionJobTopic, "Decide e paraleliza extração de áudio conforme metadados", "right")
Rel(orchestrator, audioTranscriptionJobTopic, "Decide paralelização ou bypass de transcrição", "right")
Rel(orchestrator, textTranslationJobTopic, "Determina necessidade de tradução via metadados", "right")
Rel(orchestrator, textToSpeechJobTopic, "Ativa TTS conforme preferências de workflow", "right")

@enduml
