@startuml Participants.Sequence
actor Cliente
boundary Sistema
control Controlador
database BancoDeDados

Cliente -> Sistema: Enviar Dados
Sistema -> Controlador: Processar Dados
Controlador -> BancoDeDados: Salvar Dados
BancoDeDados --> Controlador: Confirmação
Controlador --> Sistema: Dados Processados
Sistema --> Cliente: Confirmação
@enduml
